/*
 * This file was automatically generated by EvoSuite
 * Sat Dec 03 18:18:31 EET 2016
 */


import static org.evosuite.runtime.EvoAssertions.assertThrownBy;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true) 
public class Course_ESTest extends Course_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      ArrayList<Instructor> arrayList0 = new ArrayList<Instructor>();
      Schedule schedule0 = new Schedule();
      Course course0 = new Course("p6D@ mY$'ngr0@\"=_", "ot_SSj", "", arrayList0, schedule0);
      String string0 = course0.toString();
      assertEquals("SubjectName: p6D@ mY$'ngr0@\"=_ CourseNo: ot_SSj SectionNo: \nInstructors: \n[]\nSchedule: \nStartDate: null FinishDate: null null\nStudents: \n[]", string0);
  }

  @Test
  public void test1()  throws Throwable  {
      ArrayList<Instructor> arrayList0 = new ArrayList<Instructor>();
      Schedule schedule0 = new Schedule();
      Course course0 = new Course("", "", "", arrayList0, schedule0);
      Schedule schedule1 = new Schedule("6plf[sz_X![D;", (String) null, (MeetingTime) null);
      course0.schedule = schedule1;
      // Undeclared exception!
      try { 
        course0.toString();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
         //
         // String index out of range: 19
         //
         assertThrownBy("java.lang.String", e);
      }
  }

  @Test
  public void test2()  throws Throwable  {
      ArrayList<Instructor> arrayList0 = new ArrayList<Instructor>();
      Schedule schedule0 = new Schedule();
      Course course0 = new Course("p6D@ mY$'ngr0@\"=_", "ot_SSj", "", arrayList0, schedule0);
      course0.enrollStudent(" isPrimary: ");
      assertEquals(0, arrayList0.size());
      assertTrue(arrayList0.isEmpty());
  }

  @Test
  public void test3()  throws Throwable  {
      ArrayList<Instructor> arrayList0 = new ArrayList<Instructor>();
      Room room0 = new Room();
      MeetingTime meetingTime0 = new MeetingTime("Mg:4", "F{/(zm[p,N\"<1'z5r", (String) null, room0);
      Schedule schedule0 = new Schedule((String) null, "Mg:4", meetingTime0);
      Course course0 = new Course((String) null, (String) null, "Mg:4", arrayList0, schedule0);
      // Undeclared exception!
      try { 
        course0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("Room", e);
      }
  }
}
